import { Metadata } from "next";

const page = () => {
  return (
    <div>blog</div>
  )
}
export const metadata: Metadata = {
  title: "وبلاگ",
  description: "Generated by create next app",
};

export default page
