import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "@/styles/global.css";

const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["arabic"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${vazirmatn.variable} antialiased dark`}
      >
        {children}
      </body>
    </html>
  );
}
